apiVersion: v1
kind: Pod
metadata:
  name: {{ include "helm.name" . }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- with .Values.imagePullSecrets }}
  imagePullSecrets:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  serviceAccountName: {{ include "helm.serviceAccountName" . }}
  securityContext:
    {{- toYaml .Values.podSecurityContext | nindent 4 }}
  containers:
    - name: toolkit
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      image: {{ include "helm.image" . }}
      imagePullPolicy: {{ .Values.image.pullPolicy }}
      resources:
        {{- toYaml .Values.resources | nindent 8 }}
    {{- if and (eq .Values.toolkit.name "platform") (.Values.config.platform) }}
      env:
        - name: PLATFORM_TOOLKIT_CONFIG_PATH
          value: "{{ .Values.config.mountPath }}"
      volumeMounts:
        - name: config-volume
          mountPath: {{ .Values.config.mountPath }}
  volumes:
    - name: config-volume
      configMap:
        name: {{ printf "%s-platform" (include "helm.name" .) }}
    {{- end -}}
  {{- with .Values.nodeSelector }}
  nodeSelector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.affinity }}
  affinity:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.tolerations }}
  tolerations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
