apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm.name" . }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - protocol: TCP
      port: 1080
      targetPort: 1080
  selector:
    {{- include "helm.selectorLabels" . | nindent 4 }}
